// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-CWWOigQeJaYW3dwxVdsNbsgQ_0tajU',
    appId: '1:160069493052:web:511be0bced5c792ec87e39',
    messagingSenderId: '160069493052',
    projectId: 'hydro-b82ad',
    authDomain: 'hydro-b82ad.firebaseapp.com',
    storageBucket: 'hydro-b82ad.appspot.com',
    measurementId: 'G-XHEF9CMVWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlDEpTtHJKG2QpZav8Bxds3IHzEdPcXo',
    appId: '1:160069493052:android:8d83c23ac974ac09c87e39',
    messagingSenderId: '160069493052',
    projectId: 'hydro-b82ad',
    storageBucket: 'hydro-b82ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsue15sigbagTwvW3eIG15HGu0T1Tto8',
    appId: '1:160069493052:ios:33c0682986a5a660c87e39',
    messagingSenderId: '160069493052',
    projectId: 'hydro-b82ad',
    storageBucket: 'hydro-b82ad.appspot.com',
    iosBundleId: 'com.example.hydropnic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsue15sigbagTwvW3eIG15HGu0T1Tto8',
    appId: '1:160069493052:ios:b8e30fb065e9cbb0c87e39',
    messagingSenderId: '160069493052',
    projectId: 'hydro-b82ad',
    storageBucket: 'hydro-b82ad.appspot.com',
    iosBundleId: 'com.example.hydropnic.RunnerTests',
  );
}
